### ISSUE TITLE
Publish 3 Raster layer

### ISSUE THREAD

**Issue by Damianofds** [Damianofds/TanzaniaWebPortal#4]
Use the geobatch flows in order to automatic preprocess them and publish on geoserver

**Comment by anortmann** [comment]
The CRS of the layers is UTM zone 36S at the moment. Should I reproject them before uploading them?

**Comment by Damianofds** [comment]
well, the reprojection is not performed for raster layer, only for vector...

anyway a reprojection is not strictly needed since the client ask for the
layer in the google mercator projection so all the layers are reprojected
on the fly by geoserver...

Anyway I think that it's worth to have all the dataset stored using the
same SRS unless there are requirements to have a mixed SRS dataset for some
reasons...

2015-08-03 19:00 GMT+02:00 Antonia notifications@github.com:

**Comment by anortmann** [comment]
Published the three SOC layers, including html info file with project description.
