### ISSUE TITLE
Configure the REAL ingestion flow for the static raster data

### ISSUE THREAD

**Issue by Damianofds** [Damianofds/TanzaniaWebPortal#7]

**Comment by Damianofds** [comment]
The flow has been published and tested ingesting [this](http://178.33.8.120/stg_geoserver/unredd/wms?service=WMS&version=1.1.0&request=GetMap&layers=unredd:SOC_pil&styles=&bbox=29.53482829761791,-11.78078630756113,40.47942796634378,-0.9919896875544858&width=768&height=757&srs=EPSG:4326&format=application/openlayers) layer

I manually assign it the style SOC I found, just to test everything was ok but I don't know if it is the proper style.
I also add another entry to the color map

```
<ColorMapEntry color="#000033" quantity="0" label="No data" opacity="0"/>
```

In order to hide no data pixels

**Comment by anortmann** [comment]
Yes, that was the style meant for it! Thanks!
So how do I ingest the other raster layers now? By copying them to /var/stg_geobatch/input/ingestStaticRasterData/ ?

**Comment by Damianofds** [comment]
Sure copy the rasters there and  cross your fingers! ;)

2015-08-04 11:50 GMT+02:00 Antonia notifications@github.com:
